name: Schedule Worker

on:
  schedule:
#   - cron: '*/5 * * * *' #每5分钟执行一次
  - cron: 0 15 10 15 * ?	#每月15日上午10:15执行任务

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        python-version: '3.10'


#     - run: ls -al
#     - run: python autoPy.py
#     - run: ls -al
    - name: run pyfile
      run: |
        python autoPy.py
 

    

