name: Schedule Worker

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
#         cache: 'poetry'


    - run: ls -al
    - run: python autoPy.py
#     - run: python /home/runner/work/autoPython/autoPy.py
