name: Schedule Worker

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        python-version: '3.10'


#     - run: ls -al
#     - run: python autoPy.py
#     - run: ls -al
    - name: run pyfile
      run: |
        python autoPy.py
 

    

