name: Schedule Worker

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'


#     - run: ls -al
#     - run: python autoPy.py
#     - run: python /home/runner/work/autoPython/autoPy.py

    - name: SSR CheckOut
      run: |
        python autoPy.py
